models/Action.php
<?php

namespace app\models;

use app\models\params\ActionDefaultStyleParams;
use app\models\params\ActionParams;
use app\models\params\ActionSaleParams;
use Yii;

/**
 * This is the model class for table "actions".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 * @property string $created_at
 * @property in $action_id
 * @property string $start_at
 * @property string $end_at
 * @property string $item_description Описание одной фишки
 * @property int $need_to_buy Кол-во фишек для получения бонуса
 * @property int $sale_point id торговой точки в которой прохолдить данная акция
 * @property int $status_id
 */
class Action extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'actions';
    }

    public function getStyle()
    {
        return $this->hasOne(ActionStyle::class, ['action_id' => 'id']);
    }

    public function getCategories()
    {
        return $this->hasMany(Category::class, ['id' => 'category_id'])->viaTable("action_categories", ['action_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at'], 'safe'],
            [['need_to_buy', 'status_id', 'category_id'], 'integer'],
            [['start_at', 'end_at'], 'string'],
            ['status_id', 'default', 'value' => ActionParams::STATUS_ACTIVE],
            [['name', 'description', 'item_description'], 'string', 'max' => 255],
        ];
    }

    public function getOrganization()
    {
        return $this->hasOne(Organization::class, ['id' => 'organization_id']);
    }

    public function getSalePoints()
    {
        return $this->hasMany(SalePoint::class, ['id' => 'sale_point_id'])->viaTable('salepoint_actions', ['action_id' => 'id']);
    }

    public function loadDefaultParams()
    {
        $this->attributes = [
            'need_to_buy' => ActionDefaultStyleParams::DEFAULT_ITEMS_COUNT
        ];
        return $this;
    }

    public function getActivity()
    {
        return $this->hasMany(ActionSale::class, ['action_id' => 'id']);
    }

    public function getActionSales()
    {
        return $this->hasMany(ActionSale::class, ['action_id' => 'id'])->where(['type' => ActionSaleParams::ITEM_TYPE_SALE]);
    }

    public function getFirstSale()
    {
        $firstSale = $this->getActionSales()->orderBy("created_at DESC")->one();
        return $firstSale;
    }

    public function getActionGifts()
    {
        return $this->hasMany(ActionSale::class, ['action_id' => 'id'])->where(['type' => ActionSaleParams::ITEM_TYPE_GIFT]);

    }

    public function isUpdated()
    {
        $attrs = ["name", "description"];
        foreach ($attrs as $attr) {
            if ($this->isAttributeChanged($attr)) {
                return true;
            }
        }
        return false;
    }

    public function markAsInModerate()
    {
        $this->status_id = ActionParams::STATUS_NEW;
        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'description' => 'Описание',
            'created_at' => 'Дата создания',
            'start_at' => 'Дата начала',
            'end_at' => 'Дата окончания',
            'item_description' => 'Одна фишка',
            'need_to_buy' => 'Need To Buy',
            'sale_point' => 'Торговая точка',
            'status_id' => 'Статус акции',
        ];
    }

    /**
     * {@inheritdoc}
     * @return ActionsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ActionsQuery(get_called_class());
    }
}

models/ActionSale.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "action_sales".
 *
 * @property int $id
 * @property int $action_id
 * @property int $user_id
 * @property string $created_at
 * @property int $type Фишка или плюшка
 */
class ActionSale extends \yii\db\ActiveRecord
{
    const TYPE_SALE = 0;
    const TYPE_GIFT = 1;
    public $count;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'action_sales';
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function getAction()
    {
        return $this->hasOne(Action::class, ['id' => 'action_id']);
    }

    public function getSalePoint()
    {
        return $this->hasOne(SalePoint::class, ['id' => 'salepoint_id']);
    }

    public function getCashier()
    {
        return $this->hasOne(Cashier::class, ['id' => 'cashier_id']);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['action_id', 'user_id', 'type', 'salepoint_id', 'cashier_id', 'lap'], 'integer'],
            [['created_at'], 'safe'],
        ];
    }

    public static function fromState(int $actionId, int $cashierId, int $salepointId, int $userId, int $lap)
    {
        $model = new static([
            'action_id' => $actionId,
            'cashier_id' => $cashierId,
            'lap' => $lap,
            'user_id' => $userId,
            'salepoint_id' => $salepointId
        ]);
        return $model;
    }

    public function setTypeGift()
    {
        $this->type = self::TYPE_GIFT;
        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'action_id' => 'Action ID',
            'user_id' => 'User ID',
            'action.name' => 'Акция',
            'user.name' => 'Пользователь',
            'created_at' => 'Дата покупки',
            'type' => 'Тип',
        ];
    }

    /**
     * {@inheritdoc}
     * @return ActionSalesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ActionSalesQuery(get_called_class());
    }
}

models/Cashier.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cashiers".
 *
 * @property int $id
 * @property int $sale_point_id
 * @property string $name
 * @property string $user_id
 * @property string $created_at
 * @property string $password
 * @property int $is_archived
 */
class Cashier extends \yii\db\ActiveRecord
{
    public $sales_count;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cashiers';
    }

    public function getSalePoints()
    {
        return $this->hasMany(SalePoint::class, ['id' => 'salepoint_id'])->viaTable('salepoint_cashiers', ['cashier_id' => 'id']);;
    }

    public function getSales()
    {
        return $this->hasMany(ActionSale::class, ['cashier_id' => 'id']);
    }

    public function getLastSaleDate()
    {
        return $this->getSales()->orderBy("created_at DESC")->one()['created_at'] ?? null;
    }

    public function getTotalSalesCount()
    {
        return $this->getSales()->count();
    }

    public function getOrganization()
    {
        return $this->hasOne(Organization::class, ['id' => 'organization_id']);
    }

    public function getGiftsCount()
    {
        return $this->getSales()->where(['type' => ActionSale::TYPE_GIFT])->count();
    }

    public function getSoldItemsCount()
    {
        return $this->getSales()->where(['type' => ActionSale::TYPE_SALE])->count();
    }

    public function validatePassword(string $password)
    {
        return $this->password == md5($password);
    }

    public static function getPasswordEncoded(string $password)
    {
        return md5($password);
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['organization_id', 'is_archived', 'user_id'], 'integer'],
            [['created_at'], 'safe'],
            [['name', 'password'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sale_point_id' => 'Sale Point ID',
            'name' => 'Name',
            'created_at' => 'Дата создания',
            'is_archived' => 'Is Archived',
        ];
    }

    /**
     * {@inheritdoc}
     * @return CashiersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CashiersQuery(get_called_class());
    }
}

views/actions/_filter.php
<?

use yii\widgets\ActiveForm;
use app\models\params\ActionParams;

?>
<div class="column">
    <? $form = ActiveForm::begin([
        'method' => 'get',
        'id' => 'actions-filter-form',
        'options' => [
            'style' => 'margin-bottom:0 !important'
        ]
    ]); ?>
    <?= $form->field($searchModel, 'status_id')->dropDownList(ActionParams::getAllStatusNames() + ['' => 'Все'],
        ['class' => '', 'onchange' => '$("#actions-filter-form").submit()']); ?>

    <? ActiveForm::end(); ?>
</div>
<!--<div class="column">
    <label for="ageRangeField">Показывать: </label>
    <select class="bg-light-2" id="ageRangeField">
        <option value="all">Все</option>
        <option value="10">10</option>
        <option value="20">20</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
</div>-->

views/actions/index.php
<?

use app\models\params\ActionParams;
use yii\grid\GridView;
use yii\helpers\Html;
use app\models\Action;

?>
<h1>Все акции </h1>
<? $this->beginBlock('action_btn'); ?>
<a href="/actions/create" class="btn btn-success margin-bottom-10 "><i
            class="typcn typcn-plus-outline"></i>Добавить акцию</a>
<? $this->endBlock(); ?>

<div class="row">

    <?= $this->render("_filter", ['searchModel' => $searchModel]); ?>
</div>

<? if (Yii::$app->session->hasFlash("success")) { ?>
    <div class="alert alert-success"><?= Yii::$app->session->getFlash("success") ?></div>
<? } ?>
<div class="row">

    <?= GridView::widget([
        'tableOptions' => [
            'tag' => false,
            'class' => 'table table-striped table-bordered display customers dataTable all-offers',
            'style' => 'width:100%'
        ],
        'dataProvider' => $actionsProvider,
        'columns' => [
            'id',
            [
                'attribute' => 'name',
                'format' => 'raw',
                'value' => function (Action $model) {
                    return "<a href='/actions/view/{$model->id}'>{$model->name}</a>";
                }
            ],
            'description',
            'start_at:datetime',
            'end_at:datetime',
            'created_at:datetime',
            [
                'attribute' => 'status_id',
                'format' => 'raw',
                'value' => function ($model) {
                    $statusClass = [ActionParams::STATUS_NEW => "new", ActionParams::STATUS_ACTIVE => 'active', ActionParams::STATUS_CLOSED => 'archived', ActionParams::STATUS_REJECTED => "rejected"];
                    return sprintf('<span class="bage %s">%s</span>',
                        $statusClass[$model->status_id] ?? '',
                        ActionParams::getStatusNameById($model->status_id));
                }
            ],
            [
                'header' => 'Плюсы',
                'value' => function (Action $model) {
                    return $model->getActionSales()->count();
                }
            ],
            [
                'header' => 'Бонусы',
                'value' => function (Action $model) {
                    return $model->getActionGifts()->count();
                }
            ],
            [
                'header' => 'Действия',
                'class' => \yii\grid\ActionColumn::class,
                'buttons' => [
                    'update' => function ($url, $model) {
                        return sprintf('<a class="bage edit" href="/actions/%d/update" ><i class="fa fa-pencil"></i></a>', $model->id);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<i class="fa fa-trash"></i>', "/actions/{$model->id}/move-to-archive", [
                            'data-method' => 'post',
                            'class' => 'bage archive'
                        ]);

                    }
                ],
                'template' => '{update} {delete}',
            ]
            // ...
        ],
    ]) ?>
</div>

views/actions/view.php
<?

use app\models\params\ActionParams;

?>
<script>
    function getExpiration(current, endAt) {

        var diffTime = endAt.getTime() - current.getTime();
        console.log(diffTime);
        if (isNaN(diffTime)) {
            return "Бессрочно";
        }
        if (diffTime < 0) {
            return "Бессрочно";
        }
        var days = Math.floor(diffTime / (1000 * 60 * 60 * 24));
        var hours = Math.floor((diffTime - (86400000 * days)) / (1000 * 60 * 60));
        var minutes = Math.floor((diffTime - (86400000 * days) - (3600000 * hours)) / 60000);
        return "Истекает через: " + days + "дн. " + hours + "ч. ";
    }
</script>
<div class="row">
    <div class="col-md-4 margin-bottom-20">
        <div class="box-content card">
            <h4 class="box-title">Карта акции</h4>
            <div class="card-content">
                <div class="card_promo card-offer" id="promo"
                     style="background: <?= $model->style->action_bg_color ?>;position: static; transform: none; margin: 0 auto;">
                    <div class="card_promo-header card-header">
                        <!--Здесь логотип-->
                        <div class="card_promo-header-logo company-logo"
                             style="background-image: url(/<?= $model->style->logo_url ?>);"></div>
                        <!--Здесь цвет текста-->
                        <div class="card_promo-header-text company-offer"
                             style="color: <?= $model->style->action_text_color ?>;">
                            <!--Здесь текст из textarea -->
                            <?= $model->description ?>
                        </div>
                    </div>
                    <div class="card_promo-container card-content card-content-padding fishki">
                        <!--Здесь меняем класс, в зависимости от выбранного кол-ва фишек: fishek-3, fishek-4... -->
                        <ol class="card_promo-fishki row">
                            <li class="col active"
                                style="fill: <?= $model->style->active_item_bg_color ?>; stroke: <?= $model->style->active_item_border_color ?>; color: <?= $model->style->active_item_text_color ?>">
                                <svg version="1.1" viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet"
                                     class="svg-content">
                                    <circle stroke-width="20" stroke-miterlimit="20" cx="250" cy="250" r="240"></circle>
                                </svg>
                            </li>
                            <?
                            $pos = 0;
                            while ($pos++ < $model->need_to_buy - 1) { ?>
                                <!-- здесь лупим фишки-->
                                <li class="col"
                                    style="fill: <?= $model->style->item_bg_color ?>; stroke: <?= $model->style->item_border_color ?>; color: <?= $model->style->item_text_color ?>">
                                    <svg version="1.1" viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet"
                                         class="svg-content">
                                        <circle stroke-width="20" stroke-miterlimit="20" cx="250" cy="250"
                                                r="240"></circle>
                                    </svg>
                                </li>
                            <? } ?>
                            <li class="col"
                                style="fill: <?= $model->style->last_item_bg_color ?>; stroke: <?= $model->style->last_item_border_color ?>; color: <?= $model->style->last_item_text_color ?>;">
                                <svg version="1.1" viewBox="0 0 500 500" preserveAspectRatio="xMinYMin meet"
                                     class="svg-content">
                                    <circle stroke-width="20" stroke-miterlimit="20" cx="250" cy="250" r="240"></circle>
                                </svg>
                                <!--Здесь цвет такой же, как у обводки плюшки...
                                    <span class="num" style="color:<?= $model->style->last_item_border_color ?>;">5</span>-->
                                <!--Здесь border и color такой же, как у обводки плюшки и фон, как у плюшки...

                                <div class="plshk-count" style="border-color: #000; color: #000; background: #caa170;">
                                    0
                                </div>-->
                            </li>
                        </ol>
                    </div>
                    <!--Здесь фон и цвет текста подвала -->
                    <div class="card_promo-footer card-footer"
                         style="color: <?= $model->style->footer_text_color ?>; background: <?= $model->style->footer_bg_color ?>;">
                        <div class="row">
                            <div class="column card-company-name">
                                <?= $model->organization->name; ?>
                            </div>
                            <div class="column text-right">
                                <script>
                                    document.write(getExpiration(new Date(), new Date(" <?= $model->end_at; ?>")));
                                </script>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="card-content">
                <table class="table table-hover no-margin">
                    <tbody>
                    <tr>
                        <td>ID</td>
                        <td>
                            <?= $model->id ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Название</td>
                        <td>
                            <?= $model->name ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Статус</td>
                        <td>
                            <?
                            $statusClass = [ActionParams::STATUS_NEW => "new", ActionParams::STATUS_ACTIVE => 'active', ActionParams::STATUS_CLOSED => 'archived', ActionParams::STATUS_REJECTED => "rejected"];
                            echo sprintf('<span class="bage %s">%s</span>',
                                $statusClass[$model->status_id] ?? '',
                                ActionParams::getStatusNameById($model->status_id));
                            ?>
                        </td>
                    </tr>
                    <?
                    if ($model->firstSale) {
                        ?>
                        <tr>
                            <td>Старт</td>
                            <td>
                                <?= date("d.m.Y H:i", strtotime($model->firstSale->created_at)) ?> ТТ <a
                                        href="/sale-points/update/<?= $model->firstSale->salePoint->id; ?>"><?= $model->firstSale->salePoint->name; ?></a>.
                                Кассир:
                                <a href="/cashiers/update/<?= $model->firstSale->cashier->id; ?>"><?= $model->firstSale->cashier->name; ?></a>
                            </td>
                        </tr>
                    <? } ?>
                    <tr>
                        <td>Торговые Точки</td>
                        <td>
                            <? foreach ($model->salePoints as $salePoint): ?>
                                <h5><a href="/sale-points/update/<?= $salePoint->id ?>"><?= $salePoint->name ?></a></h5>
                            <? endforeach; ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="box-footer text-center">
                <a href="/actions/<?= $model->id ?>/update" class="btn btn-default btn-sm">Редактировать</a>
                <? if ($model->status_id == ActionParams::STATUS_ACTIVE) { ?>
                    <a href="/actions/<?= $model->id ?>/move-to-archive" class="btn btn-danger btn-sm">Завершить
                        акцию</a>
                <? } ?>
                <? if ($model->status_id == ActionParams::STATUS_CLOSED) { ?>
                    <a href="/actions/<?= $model->id ?>/activate" class="btn btn-success btn-sm">Активировать
                        акцию</a>
                <? } ?>
            </div>
        </div>
    </div>
    <div class="col-md-4 margin-bottom-20">
        <div class="box-content card">
            <h4 class="box-title">Статистика акции</h4>
            <div class="card-content">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Кассир</th>
                        <th class="text-center">Плюсы</th>
                        <th class="text-center">Бонусы</th>
                    </tr>
                    </thead>
                    <tbody>
                    <? foreach ($saleStatistic->getSalePoints() as $salePoint) { ?>
                        <tr>
                            <th colspan="3" class="text-center"><a
                                        href="/sale-points/update/<?= $salePoint->id ?>"><?= $salePoint->name ?></a>
                            </th>
                        </tr>
                        <?

                        foreach ($salePoint->cashiers as $cashier) {
                            $stat = $saleStatistic->getSalesForCashierInSalePoint($cashier, $salePoint);
                            ?>
                            <tr>
                                <td><a href="/cashiers/update/<?= $cashier->id ?>"><?= $cashier->name ?></a></td>
                                <td class="text-center">
                                    <?= $stat['sales'] ?>
                                </td>
                                <td class="text-center">
                                    <?= $stat['gifts'] ?>
                                </td>
                            </tr>
                        <? } ?>
                    <? } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4 margin-bottom-20">
        <div class="box-content card">
            <h4 class="box-title">Лог активностей</h4>
            <div class="card-content" style="max-height: 80vh; overflow-y: auto">
                <ul class="notice-list">
                    <? foreach ($saleStatistic->getActivity() as $activityItem) { ?>
                        <li>
                                <span class="icon bg-<?= $activityItem->type == \app\models\ActionSale::TYPE_SALE ? "success " : "violet " ?>"><i
                                            class="fa fa-<?= $activityItem->type == \app\models\ActionSale::TYPE_SALE ? "plus" : "check" ?>-circle"></i></span>
                            <span class="title">Выдана <?= $activityItem->type == \app\models\ActionSale::TYPE_SALE ? "фишка" : "плюшка" ?>
                                : <?= $activityItem->count ?>шт.</span>
                            <span class="desc">Кассир <a
                                        href="/cashiers/update/<?= $activityItem->cashier->id ?>"><?= $activityItem->cashier->name ?></a> выдал 1 фишку по акции <a
                                        href="/actions/view/<?= $activityItem->action->id ?>">"<?= $activityItem->action->name ?>
                                    "</a> клиенту <a
                                        href="/users/view/<?= $activityItem->user->id ?>"><?= $activityItem->user->name ?></a></span>
                            <span class="time"><?= date("d.m.Y в H:i", strtotime($activityItem->created_at)) ?></span>
                        </li>
                    <? } ?>
                </ul>
            </div>
        </div>
    </div>
</div>