models/PanelModel.php
<?php
/**
 * Created by PhpStorm.
 * User: ruslan
 * Date: 29/09/2019
 * Time: 21:33
 */

namespace app\models;


use app\classes\ReferalsHistoryComposer;
use app\classes\ReferalStatReader;
use yii\base\Model;
use yii\helpers\Url;

class PanelModel extends Model
{
    private $user;
    private $referalStat;
    private $historyComposer;

    public function __construct(User $user)
    {
        $this->user = $user;
        $this->referalStat = new ReferalStatReader($user);
        $this->historyComposer = new ReferalsHistoryComposer($this->user);

    }

    public function getReferalCode()
    {
        return $this->user->getId();
    }

    public function getSiteReferalLink()
    {
        return Url::base(true) . "/site/" . $this->user->getId();
    }

    public function getRegistrationReferalLink()
    {
        return Url::base(true) . "/" . $this->user->getId();
    }

    public function getWebinarLink()
    {
        return Url::base(true) . "/webinar/" . $this->user->getId();
    }

    public function getVisits()
    {
        return $this->referalStat->getVisitsCount();
    }

    public function getHistory()
    {
        return $this->historyComposer->composeActivityHistory();
    }

    public function getRegistrations()
    {
        return $this->referalStat->getRegistrationsCount();
    }

    public function getConversion()
    {
        return $this->referalStat->getConversion();
    }

    public function getBalance()
    {
        return $this->user->balance;
    }
}

views/backoffice/edit-profile.php
<? use yii\bootstrap\ActiveForm;

$form = ActiveForm::begin([
    'options' => [
        'enctype' => 'multipart/form-data',
        'class' => 'form-horizontal'
    ],
    'fieldConfig' => [
        'template' => '{label}<div class="col-sm-9">{input}</div>{error}',
        'labelOptions' => ['class' => 'col-sm-3 control-label']
    ]
]); ?>
    <div class="row  small-spacing">
        <? if ($success) { ?>
            <div style="width:100%" class="alert alert-success"><?= $success ?></div>
        <? } ?>
    </div>
    <div class="row  small-spacing">

        <div class="col-lg-4">
            <div class="box-content " id="myTabContent-justified">
                <h4 class="box-title">Общая информация</h4>
                <div class="card-content">
                    <?= $form->field($model, "profilePhoto")->fileInput(); ?>
                    <?= $form->field($model, "name")->textInput(); ?>
                    <?= $form->field($model, "surname")->textInput(); ?>
                    <?= $form->field($model, "email")->textInput(); ?>
                    <?= $form->field($model, "referer")->textInput(); ?>
                    <?= $form->field($model, "show_contacts",['template'=>'{label}<div class="col-sm-9">{input}</div>{error}'])
                        ->checkbox(['labelOptions' => ['class' => 'col-sm-3 control-label']],false); ?>
                    <!-- <div class="form-group  row margin-top-20">
                         <label for="exampleInputFile" class="col-sm-3 control-label">Фото</label>
                         <div class="col-sm-9">
                             <input type="file" id="exampleInputFile">
                         </div>
                     </div>-->

                    <?= $form->field($model, "about")->textarea(); ?>


                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="box-content " id="myTabContent-justified">
                <h4 class="box-title">Ваши аккаунты в соцсетях:</h4>
                <div class="card-content">
                    <?= $form->field($model, "vk_link", ['template' => ' <div class="input-group-btn">
                        <label for="ig-1" class="btn btn-default"><i class="fa fa-vk"></i></label>
                    </div>{input}{error}', 'options' => ['class' => 'input-group margin-bottom-20']])->textInput(['placeholder' => 'Ссылка на профиль Вконтакте'])->label(false); ?>

                    <?= $form->field($model, "fb_link", ['template' => ' <div class="input-group-btn">
                        <label for="ig-1" class="btn btn-default"><i class="fa fa-facebook"></i></label>
                    </div>{input}{error}', 'options' => ['class' => 'input-group margin-bottom-20']])->textInput(['placeholder' => 'Ссылка на профиль Facebook'])->label(false); ?>

                    <?= $form->field($model, "ok_link", ['template' => ' <div class="input-group-btn">
                        <label for="ig-1" class="btn btn-default"><i class="fa fa-odnoklassniki"></i></label>
                    </div>{input}{error}', 'options' => ['class' => 'input-group margin-bottom-20']])->textInput(['placeholder' => 'Ссылка на профиль Одноклассники'])->label(false); ?>

                    <?= $form->field($model, "mm_link", ['template' => ' <div class="input-group-btn">
                        <label for="ig-1" class="btn btn-default"><i class="fa fa-at"></i></label>
                    </div>{input}{error}', 'options' => ['class' => 'input-group margin-bottom-20']])->textInput(['placeholder' => 'Ссылка на профиль Мой мир'])->label(false); ?>

                    <?= $form->field($model, "instagram_link", ['template' => ' <div class="input-group-btn">
                        <label for="ig-1" class="btn btn-default"><i class="fa fa-instagram"></i></label>
                    </div>{input}{error}', 'options' => ['class' => 'input-group margin-bottom-20']])->textInput(['placeholder' => 'Ссылка на профиль Инстаграм'])->label(false); ?>


                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="box-content " id="myTabContent-justified">
                <h4 class="box-title">Безопасность</h4>
                <div class="card-content" style="padding: 0 15px;">
                    <?= $form->field($model, "new_password", ['template' => '{label}{input}', 'labelOptions' => ['class' => 'control-label']])->textInput(); ?>
                    <?= $form->field($model, "repeat_password", ['template' => '{label}{input}', 'labelOptions' => ['class' => 'control-label']])->textInput(); ?>
                    <!-- <div class="form-group">
                         <label for="pass" class="control-label">Новый пароль</label>
                         <input type="password" class="form-control" id="pass" placeholder="Новый пароль">
                     </div>
                     <div class="form-group">
                         <label for="pass" class="control-label">Повтор нового пароля</label>
                         <input type="password" class="form-control" id="pass" placeholder="Новый пароль">
                     </div>-->

                    <blockquote>
                        <p>Пароль от Личного кабинета и приложения совпадает.</p>
                    </blockquote>
                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary btn-sm btn-block">Сохранить</button>
        </div>
        <div class="col-md-4"></div>
    </div>
<? ActiveForm::end() ?>

views/backoffice/finances.php
<?

use yii\grid\GridView;
use yii\bootstrap\ActiveForm;

?>
    <div style="width:100%" class="row  small-spacing">
        <div class="col-md-4">
            <div class="table-responsive box-content">
                <h4 class="box-title">Личный баланс</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Показатель</th>
                            <th>Сумма</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Текущиий баланс</th>
                            <td><strong><?= $model->balance ?> <span class="text-danger">Cb+</span></strong>
                            </td>
                        </tr>
                        <tr>
                            <th>Ожиданиет вывода</th>
                            <td><strong>0000 руб.</strong></td>
                        </tr>
                        <tr>
                            <th>Всего выведено</th>
                            <td><strong>0000 руб.</strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>


            <div class="table-responsive box-content">
                <h4 class="box-title">Пополнение баланса</h4>
                <div class="dropdown js__drop_down">
                    <h4 class="box-title"><strong class="text-danger">1 Cb+ = 1 руб.</strong></h4>
                </div>
                <? $balanceForm = ActiveForm::begin([
                'fieldConfig' => [
                    'template' => '{error}{input}',
                    'labelOptions' => ['class' => 'col-sm-3 control-label']
                ]
            ]); ?>
                    <div class="input-group margin-bottom-20">

                        <!-- <input type="number" class="form-control" placeholder="Введиите сумму">-->
                        <?= $balanceForm->field($balanceFormModel, 'sum')->textInput(['placeholder' => 'Введите сумму пополнения']) ?>
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-success no-border"><i class="fa fa-paper-plane text-white"></i>
                    </button>
                            </div>
                    </div>
                    <? ActiveForm::end(); ?>
            </div>
            
            
            <div class="table-responsive box-content">
                <h4 class="box-title">Вывод средств</h4>
                <div class="dropdown js__drop_down">
                    <h4 class="box-title"><strong class="text-danger">1 Cb+ = 1 руб.</strong></h4>
                </div>
                <? $outForm = ActiveForm::begin([
                'fieldConfig' => [
                    'template' => '{input}{error}',
                    'labelOptions' => ['class' => 'col-sm-3 control-label']
                ]
            ]); ?>
                    <div class="input-group margin-bottom-20">

                        <!-- <input type="number" class="form-control" placeholder="Введиите сумму">-->
                        <?= $outForm->field($moneyOutForm, 'sum')->textInput(['placeholder' => 'Введите сумму вывода']) ?>
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-success no-border"><i class="fa fa-paper-plane text-white"></i>
                    </button>
                            </div>
                    </div>
                    <? ActiveForm::end(); ?>
            </div>

            <div class="table-responsive box-content bg-muted">
                <h4 class="box-title text-muted">Перевод средств</h4>
                <div class="dropdown js__drop_down">
                    <h4 class="box-title"><strong class="text-muted">мин. 1000 Cb+</strong></h4>
                </div>
                <div class="input-group margin-bottom-20">
                    <!-- <input type="number" class="form-control" placeholder="Введиите сумму">-->
                    <div class="form-group field-moneyoutform-sum row" style="margin: 0 !important;">
                        <input disabled="disabled" type="text" id="moneyoutform-sum" class="form-control col-xs-6" name="MoneyOutForm[sum]" placeholder="ID или телефон пользователя" aria-invalid="false">
                        <input disabled="disabled" type="text" id="moneyoutform-sum" class="form-control  col-xs-6" name="MoneyOutForm[sum]" placeholder="Введите сумму перевода" aria-invalid="false">
                        <p class="help-block help-block-error"></p>
                    </div>
                    <div class="input-group-btn">
                        <button type="submit" class="btn no-border"><i class="fa fa-paper-plane text-white"></i>
                    </button>
                    </div>
                </div>
                <h5 class="text-muted">Перевод средств между пользователями временно заблокирован</h5>
            </div>

        </div>

        <div class="col-md-8">
            <div class="table-responsive box-content">
                <?= GridView::widget([
                'dataProvider' => $transactionsList,
                'columns' => [
                    'id',
                    'sum',
                    [
                        'attribute' => 'created_at',
                        'value' => function ($model) {
                            return date("d.m.Y в H:i", $model->created_at);
                        }
                    ],
                    [
                        'attribute' => 'type',
                        'value' => function ($model) {
                            return \app\models\Transaction::$transactionTypeNames[$model->type] ?? '';
                        }
                    ],
                    [
                        'attribute' => 'status',
                        'value' => function ($model) {
                            return \app\models\Transaction::$statusNames[$model->status] ?? '';
                        }
                    ]
                ]
            ]); ?>
            </div>
        </div>
    </div>

views/backoffice/panel.php
<?

use yii\bootstrap\ActiveForm;

?>
    <div class="row small-spacing">
        <div class="col-lg-4 col-md-12 col-xs-12">
            <div class="box-content">
                <h4 class="box-title"><i class="ico glyphicon glyphicon-link"></i>Мой партнёрский код: <span class="text-danger"><?= $model->getReferalCode(); ?></span></h4>

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Ссылка на сайт</th>
                            <td>
                                <button type="button" data-clipboard-text="<?= $model->getSiteReferalLink() ?>" class="referal_link btn btn-icon btn-icon-right btn-sm btn-block"><i
                                    class="ico fa fa-flag"></i><?= $model->getSiteReferalLink() ?>
                        </button>
                            </td>
                        </tr>
                        <tr>
                            <th>Регистрация</th>
                            <td>
                                <button type="button" data-clipboard-text="<?= $model->getRegistrationReferalLink() ?>" class="referal_link btn btn-icon btn-icon-right btn-sm btn-block"><i
                                    class="ico fa fa-flag"></i><?= $model->getRegistrationReferalLink() ?>
                        </button>
                            </td>
                        </tr>
                        <tr>
                            <th>Ссылка на вебинар</th>
                            <td>
                                <button type="button" data-clipboard-text="<?= $model->getWebinarLink() ?>" class="referal_link btn btn-icon btn-icon-right btn-sm btn-block"><i
                                    class="ico fa fa-flag"></i><?= $model->getWebinarLink() ?>
                        </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-xs-12">
            <div class="box-content">
                <h4 class="box-title"><i class="ico fa fa-pie-chart"></i>Сводка</h4>
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Всего переходов</th>
                            <td>
                                <?= $model->visits ?>
                            </td>
                        </tr>
                        <tr>
                            <th>Всего регистраций</th>
                            <td>
                                <?= $model->registrations ?>
                            </td>
                        </tr>
                        <tr>
                            <th>Конверсия</th>
                            <td>
                                <?= $model->conversion; ?>%</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-xs-12">
            <div class="box-content">
                <h4 class="box-title"><i class="ico fa fa-money"></i>Баланс</h4>
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Текущиий баланс</th>
                            <td><strong><?= $model->getBalance(); ?> <span class="text-danger">Cb+</span></strong>
                            </td>
                        </tr>
                        <tr>
                            <th>Ожиданиет вывода</th>
                            <td><strong>0 000 <span class="text-danger">Cb+</span></strong></td>
                        </tr>
                        <tr>
                            <th>Всего выведено</th>
                            <td><strong>0 000 <span class="text-danger">Cb+</span></strong></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row small-spacing">
        <div class="col-md-6">
            <div class="box-content">
                <h4 class="box-title"><i class="ico fa fa-calendar"></i>Последние действия</h4>
                <div class="">
                    <? if (empty($model->history)) { ?>
                        <h3>Пока нет активности:(</h3>
                        <? } ?>

                            <ul class="notice-list log-list">
                                <? foreach ($model->history as $historyItem) { ?>
                                    <li>
                                        <span class="icon bg-warning"><i class="fa fa-user-plus"></i></span>
                                        <span class="title">Новый Реферал</span>
                                        <span class="desc"><a href="profile.html"><?= $historyItem->name ?></a> Статус: <span
                                    class="agent-acc"><?= \app\models\User::$userTypeLabels[$historyItem->user_type] ?></span> </span>
                                        <span class="time"><?= $historyItem->getCreateDateFormatted() ?></span>
                                    </li>
                                    <? } ?>
                            </ul>
                            <!-- <ul class="notice-list">
                 <li>
                     <span class="icon bg-warning"><i class="fa fa-user-plus"></i></span>
                     <span class="title">Новый Реферал</span>
                     <span class="desc"><a href="profile.html">Виталий</a>, г. Калининград. Статус: <span
                                 class="partner-acc">Партнёр</span> </span>
                     <span class="time">19.09.2019 в 10:30</span>
                 </li>
                 <li>
                     <span class="icon bg-warning"><i class="fa fa-user-plus"></i></span>
                     <span class="title">Новый Реферал</span>
                     <span class="desc"><a href="profile.html">Виталий</a>, г. Калининград. Статус: <span
                                 class="agent-acc">Агент</span> </span>
                     <span class="time">19.09.2019 в 10:30</span>
                 </li>
                 <li>
                     <span class="icon bg-warning"><i class="fa fa-user-plus"></i></span>
                     <span class="title">Новый Реферал</span>
                     <span class="desc"><a href="profile.html">Виталий</a>, г. Калининград. Статус: <span
                                 class="user-acc">Пользователь</span> </span>
                     <span class="time">19.09.2019 в 10:30</span>
                 </li>
                 <li>
                     <span class="icon bg-success"><i class="fa fa-plus-circle"></i></span>
                     <span class="title">Новая Торговая Точка</span>
                     <span class="desc"><a href="tochka.html">"Ларёк вокзал"</a> г. Калининград. Статус: <span
                                 class="start-tt">Старт</span></span>
                     <span class="time">19.09.2019 в 10:30</span>
                 </li>
                 <li>
                     <span class="icon bg-success"><i class="fa fa-plus-circle"></i></span>
                     <span class="title">Новая Торговая Точка</span>
                     <span class="desc"><a href="tochka.html">"Ларёк вокзал"</a> г. Калининград. Статус: <span
                                 class="biz-tt">Бизнес</span></span>
                     <span class="time">19.09.2019 в 10:30</span>
                 </li>
                 <li>
                     <span class="icon bg-success"><i class="fa fa-plus-circle"></i></span>
                     <span class="title">Новая Торговая Точка</span>
                     <span class="desc"><a href="tochka.html">"Ларёк вокзал"</a> г. Калининград. Статус: <span
                                 class="serv-tt">Сервис</span></span>
                     <span class="time">19.09.2019 в 10:30</span>
                 </li>
             </ul>-->
                </div>
            </div>
            <!-- /.box-content -->
        </div>
        <div class="col-md-6">
            <div class="box-content">
                <h4 class="box-title"><i class="ico fa fa-pie-chart"></i>Инструменты</h4>
                <div class="box-body">
                    <ul class="nav nav-pills nav-stacked">
                        <!-- <li>
                        <a href="#"><i class="fa fa-file-text"></i> Скрипт переписки в соцсетях
                            <span class="label-right bg-primary pull-right">новое</span>
                        </a>
                    </li> -->
                        <li>
                            <a href="https://comeback.plus/files/self_vc.psd" target="_blank"><i class="fa fa-download"></i> Шаблон визиток
                        </a>
                        </li>
                        <!--<li>
                        <a href="#"><i class="fa fa-download" target="_blank"></i> Презентация партнерской программы
                        </a>
                    </li>-->
                        <li>
                            <a href="https://comeback.plus/files/compred-web.pdf" target="_blank"><i class="fa fa-download"></i> Презентация для владельцев бизнеса (веб)
                        </a>
                        </li>
                        <li>
                            <a href="https://comeback.plus/files/compred.pdf" target="_blank"><i class="fa fa-download"></i> Презентация для владельцев бизнеса (для печати)
                        </a>
                        </li>
                        <li>
                            <a href="https://comeback.plus/files/about.pdf" target="_blank"><i class="fa fa-download"></i> О сервисе для бизнеса
                        </a>
                        </li>
                        <li>
                            <a href="https://comeback.plus/files/buklet_4_tt.pdf" target="_blank"><i class="fa fa-download"></i> Буклет для владельцев бизнеса
                        </a>
                        </li>
                        <li>
                            <a href="https://comeback.plus/files/stickers.pdf" target="_blank"><i class="fa fa-download"></i> Макеты наклеек для торговых точек
                        </a>
                        </li>
                        <li>
                            <a href="https://comeback.plus/files/manual_admin.pdf" target="_blank"><i class="fa fa-file-text"></i> Руководство пользователя для администраторов
                        </a>
                        </li>
                        <li>
                            <a href="https://comeback.plus/files/manual_cashier.pdf" target="_blank"><i class="fa fa-file-text"></i> Руководство пользователя для кассиров
                        </a>
                        </li>
                        <li>
                            <a href="https://comeback.plus/files/manual_full.pdf" target="_blank"><i class="fa fa-file-text"></i> Полное руководство для владельцев бизнеса
                        </a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /.box-content -->
        </div>
    </div>
    <script>
        $(document).ready(function() {
            (new ClipboardJS('.referal_link')).on('success', function(e) {
                alert('Скопировано!');
            });
        })
    </script>

views/backoffice/plan.php
<?php

use app\models\User;

?>
<? if ($success) { ?>
    <div class="alert alert-success"><?= $success ?></div>
<? } ?>
<? if ($error) { ?>
    <div class="alert alert-danger"><?= $error ?></div>
<? } ?>
<div class="pricing-plan">
    <div class="pricing-table">
        <div class="col col-first">
            <div class="thead">
                <div class="center-v">Выбирайте свой вариант</div>
            </div>
            <div class="td">Новый пользователь приложения</div>
            <div class="td">Новый агент</div>
            <div class="td">Новый партнёр</div>
            <div class="td">Новая Торговая точка (План Старт)</div>
            <div class="td">Новая Торговая точка (План Бизнес)</div>
            <div class="td">Доход с оборота 1-й линии</div>
            <div class="td">Доход с оборота 2-й линии</div>
            <div class="td">Доход с оборота 3-й линии</div>
            <div class="td">Доход с оборота 4-й линии</div>
            <div class="td">Доход с оборота 5-й линии</div>
            <div class="td"></div>
        </div>
        <div class="col">
            <div class="thead bg-gray">
                <h4>Пользователь</h4>
                <div class="price">
                    <span class="number">0</span>
                    <span class="small_number">00</span>
                    <span class="time">руб.</span>
                </div>
            </div>
            <div class="td">1</div>
            <div class="td">300</div>
            <div class="td">1000</div>
            <div class="td">500</div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>

            <div class="td"><a style="<?= ($user->user_type != User::USER_TYPE_DEFAULT ? "visibility:hidden" : "") ?>"
                               href="" class="btn-order btn-gray">АКТИВИРОВАНО</a></div>
        </div>
        <div class="col">
            <div class="thead bg-purple">
                <h4>Агент</h4>
                <div class="price">
                    <span class="number">30</span>
                    <span class="small_number">000</span>
                    <span class="time">руб</span>
                </div>
            </div>
            <div class="td">1</div>
            <div class="td">6 000</div>
            <div class="td">20 000</div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td">400 руб/мес</div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td"><i class="fa fa-times"></i></div>
            <? if ($user->user_type == User::USER_TYPE_DEFAULT && $user->user_type != User::USER_TYPE_PARTNER) { ?>
                <div class="td"><a href="/backoffice/finances/buy-agent" class="btn-order">АКТИВИРОВАТЬ</a></div>
            <? } else if ($user->user_type == User::USER_TYPE_AGENT) { ?>
                <div class="td"><a href="#" class="btn-order">АКТИВИРОВАНО</a></div>
            <? } ?>
        </div>
        <div class="col col-featured">
            <div class="thead bg-main-2">
                <h4>Партнёр</h4>
                <div class="price">
                    <span class="number">100</span>
                    <span class="small_number">000</span>
                    <span class="time">руб</span>
                </div>
            </div>
            <div class="td">1</div>
            <div class="td">9 000</div>
            <div class="td">30 000</div>
            <div class="td"><i class="fa fa-times"></i></div>
            <div class="td">600 руб/мес</div>
            <div class="td">10%</div>
            <div class="td">5%</div>
            <div class="td">2%</div>
            <div class="td">1%</div>
            <div class="td">0.5%</div>
            <? if (in_array($user->user_type, [User::USER_TYPE_AGENT, User::USER_TYPE_DEFAULT])) { ?>
                <div class="td"><a href="/backoffice/finances/buy-partner" class="btn-order">АКТИВИРОВАТЬ</a></div>
            <? } else if ($user->user_type == User::USER_TYPE_PARTNER) { ?>
                <div class="td"><a href="/backoffice/finances/buy-partner" class="btn-order">АКТИВИРОВАНО</a></div>
            <? } ?>
        </div>
    </div>
</div>

views/backoffice/tree.php
<h1>Дерево приглашений</h1>
<div id="jstree_demo_div"></div>
<script>
    $(document).ready(function () {
        $('#jstree_demo_div').jstree({
            'core': {
                'data': <?=$treeJSON?>
            }
        });
    });
</script>